# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Iron CMS
email: mrlsd@ya.ru
description: > # this means to ignore newlines until "baseurl:"
  Iron CMS - Inspired by Rust - flexible, fast, extensible, reliable CMS based on Iron Framework..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iron-cms.github.io" # the base hostname & protocol for your site
# url: "http://localhost:4000"
github_username:  mrlsd
project_repository: iron-cms
facebook_username: evgeny.ukhanov

# Google Analitics
google-analytics: "UA-86657406-1"

# Build settings
markdown: kramdown
theme: minima
